# Generated by Django 5.0.3 on 2024-03-24 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="session_id",
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
