# Generated by Django 5.0.3 on 2024-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_chat_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="session_id",
            field=models.IntegerField(default=1),
        ),
    ]
